config/routes.rb
Rails.application.routes.draw do
  resources :actor_movies
  resources :movies
  resources :addresses
  resources :categories
  resources :actors
  resources :directors

  root to: 'application#index'

  get '/persons/new', to: 'people#new'
  post '/persons/create', to: 'people#create'
  get '/persons/all', to: 'people#show_all'
  get '/persons/actor', to: 'people#show_actors'
  get '/persons/director', to: 'people#show_directors'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/application/index.html.erb
<h1 align="center">Lab 09</h1>
<h2>Models</h2>
<%= link_to 'Actors', actors_path %><br>
<%= link_to 'Director', directors_path %><br>
<%= link_to 'Movie', movies_path %><br>
<%= link_to 'Category', categories_path %><br>
<%= link_to 'Address', addresses_path %><br>
<%= link_to 'Actor-Movie', actor_movies_path %><br>

<br>

<h2>Person Form</h2>
<%= link_to 'Create Person', persons_new_path %><br>

<br>

<h2>All People (through /persons)</h2>
<%= link_to 'Actors', persons_actor_path %><br>
<%= link_to 'Directors', persons_director_path %><br>

<br>

<h2>Categories</h2>
<%= link_to 'New Category', new_category_path %><br>
<%= link_to 'View Categories', categories_path %><br>

<br>

<h2>New Movie</h2>
<%= link_to 'New Movie', new_movie_path %>